_target_: jamun.model.arch.E3Conv
_partial_: true
irreps_out: "1x1e"
irreps_hidden: "120x0e + 32x1e"
irreps_sh: "1x0e + 1x1e"
n_layers: 5
radial_edge_embedder_factory:
  _target_: jamun.model.embedding.RadialEdgeEmbedder
  _partial_: true
  radial_edge_attr_dim: 32
  basis: "gaussian"
  cutoff: true
  max_radius: ${model.max_radius}
bond_edge_embedder_factory:
  _target_: jamun.model.embedding.BondEdgeEmbedder
  _partial_: true
  bonded_edge_attr_dim: 32
atom_embedder_factory:
  _target_: jamun.model.embedding.AtomEmbeddingWithResidueInformation
  _partial_: true
  atom_type_embedding_dim: 8
  atom_code_embedding_dim: 8
  residue_code_embedding_dim: 32
  residue_index_embedding_dim: 8
  use_residue_sequence_index: false
  num_atom_types: 20
  max_sequence_length: 10
  num_atom_codes: 10
  num_residue_types: 25
hidden_layer_factory:
  _target_: e3tools.nn.SeparableConvBlock
  _partial_: true
output_head_factory:
  _target_: e3tools.nn.EquivariantMLP
  _partial_: true
  irreps_hidden_list:
    - ${model.arch.irreps_hidden}
max_radius: ${model.max_radius}
