_target_: jamun.model.arch.MoleculeGNSWrapper
_partial_: true
latent_dim: 256
num_message_passing_steps: 5
base_mlp_hidden_dim: 1024
base_mlp_depth: 2
head_mlp_hidden_dim: 256
head_mlp_depth: 1
activation: silu
sh_lmax: 3
max_radius: ${model.max_radius}
bessel_num_bases: 8
bond_edge_embedder_factory:
  _target_: jamun.model.embedding.BondEdgeEmbedder
  _partial_: true
  bonded_edge_attr_dim: 32
  input_as_atom_graphs: true
atom_embedder_factory:
  _target_: jamun.model.embedding.AtomEmbeddingWithResidueInformation
  _partial_: true
  atom_type_embedding_dim: 8
  atom_code_embedding_dim: 8
  residue_code_embedding_dim: 32
  residue_index_embedding_dim: 8
  use_residue_sequence_index: false
  num_atom_types: 20
  max_sequence_length: 10
  num_atom_codes: 10
  num_residue_types: 25
  input_as_atom_graphs: true
